---

reboots_during_run: yes
upgrade_dist: yes
install_ngrok: no

systemname: kapture
kapture_user: kapture

kapture_app_branch: stable  # stable / unstable

download_path: /var/lib/kapture/downloads  # should be mounted and handled automatically with usbmount

transmission_random_password: yes

flexget_check_frequency: 15   # minutes
flexget_cron_enabled: false   # allow daemon to take over

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA07uidLJnAxF7PR+NOAyg/6EwECE2SrBHOiwT73UdOHLAomFmG/z7dCk+WU8Wo68z0T0VT06xgfBWgmpZD2VS6F24cPzibJBFuEZndT9J0BcQmav3fMzKl9LYZ3lNulPS8MJygG/5EeyrfNvFHB4cDdvucogcFc8VUx4omJo407Ip8FAiwBocqqV7WfOeMBPoj16HvERJjEDMk6j1e4pp25w0Ss7qGJ+tT3iR1zkS71J2dgAWFou84FyuiRwOA9UQn7pdNn5x7SGPckh+smInSgXEBWmRlhR63cUFXggr1QnCu8msClFqoh6HlBts/J69i1d29N0Uzmz7XYA/sM2F4w== gaieges@typhoid.local"

# mkpasswd --method=SHA-512 "kapture is the bombest thing ever" 'FunkySalt5'
initial_user_password: $6$FunkySalt5$YBrkBxf7D1wKFaNiNwWkv8IPEApb7V/rfsBg8o6WPmCIeKhd79gpJVhvvleynYfTH4an8/CyGWacArg6eGsDu1
