---
# tasks file for roles/flexget

#######################
### FLEXGET STUFF
#######################

# should already have pip from initial setup
- name: install flexget and deps
  pip: name="{{ item.name }}" version="{{ item.version | default(omit) }}"
  with_items:
    - {name: flexget, version: 2.0.19 }
    - {name: transmissionrpc }
  notify: restart transmission

- name: create flexget config dir
  file:
    dest: "~{{ kapture_user }}/.flexget"
    state: directory
    owner: "{{ kapture_user }}"
    recurse: yes

- name: flexget config file
  template:
    src: flexget-config.yml.j2
    dest: "~{{ kapture_user }}/.flexget/config.yml"
    mode: 0644
    owner: "{{ kapture_user }}"

- name: flexget cron job
  cron:
    name: flexget
    user: "{{ kapture_user }}"
    minute: "*/{{ flexget_check_frequency }}"
    job: "/usr/bin/python2.7 /usr/local/bin/flexget --cron execute --disable-tracking"
