---
##############################################
### SETUP BANANAPI (meant to be remote)
##############################################

- hosts: all
  become: yes
  roles:
    - initial-setup
    - plex
    - transmission
    - netatalk
    - flexget
    - kapture
