---


- hosts: all
  become: yes
  roles:
    - role: plex
      tags: plex

    - role: transmission
      tags: transmission

    - role: flexget-daemon
      tags: flexget-daemon

    - role: kapture
      tags: kapture
      
    - role: flexget-cron
      tags: flexget-cron

    - role: netatalk
      tags: netatalk
      
    - role: lucazz.cifs_server
      tags: lucazz.cifs_server
