---
# sets up a disk based on the defaults and ansible args

# Don't think we want to do this, especially on new builds.
# Keeping it in in case it's needed
# - name: fsck usb disk just to be safe
#   command: "e2fsck -fp {{ storage_block_device }}"

- name: format partition
  filesystem:
    fstype: ext4
    device: "{{ storage_block_device }}"
    resizefs: yes
    opts: -L media-storage

- name: trigger automount process from udev / usbmount
  command: udevadm trigger --action=add --sysname-match=sd*


# additional disk spindown tweaks?
