---
# tasks file for roles/kapture

- meta: flush_handlers

#######################
### System STUFF
#######################

- name: set hostname
  hostname: 
    name: "{{ systemname }}"
  register: hostname_task

- name: trigger restart handler if needed
  command: /bin/true # noop
  when: hostname_task.changed and pi is defined and pi
  notify: restart device

- name: ensure kapture group is setup correctly
  group: name=kapture system=yes state=present

- name: "ensure {{ kapture_user }} user is setup correctly"
  user:
    groups: sudo,kapture
    name: "{{ kapture_user }}"
    createhome: yes
    home: /var/lib/kapture
    state: present

- name: ensure admin user is in kapture group
  user: 
    name: "{{ ansible_ssh_user }}" 
    groups: kapture,sudo
  when: pi is defined and pi

- name: ensure vagrant user is in kapture group
  user: name=vagrant groups=kapture,sudo
  when: vagrant is defined and vagrant

- name: ensure users are in kapture group
  user:
    name: "{{ item }}"
    groups: kapture
    state: present
  with_items:
    - plex
    - debian-transmission

- name: ensure kapture user is created and in right groups
  user:
    groups: sudo,kapture
    name: "{{ kapture_user }}"
    state: present

- name: ensure nobody user is in kapture group
  user:
    name: nobody
    groups: kapture,nogroup
    state: present
  notify: restart netatalk

- name: ensure that directory points to usb disk spot if pi
  file:
    dest: /var/lib/kapture
    state: link
    path: /media/usb
  when: pi is defined and pi

- name: set permissions on default download directory
  file:
    recurse: yes
    path: /var/lib/kapture
    mode: 0775
    group: kapture

- name: install pip from apt
  apt: pkg=python-pip state=present
  when: ansible_lsb.id != "Raspbian"

- block:
    - name: install pip using easy_install if Raspbian
      apt: name=python-setuptools state=present
    - easy_install: name=pip state=present
  when: ansible_lsb.id == "Raspbian"

- name: install ansible for running locally
  pip: 
    name: "{{ item.name }}" 
    version: "{{ item.version | default(omit) }}" 
    state: present
  with_items:
    - { name: ansible }
    - { name: setuptools, version: 23.0.0 }

- name: install ngrok if needed
  command: npm install -g ngrok
  when: install_ngrok

- name: ensure sudo group has passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo   ALL=(ALL:ALL) ALL$"
    line:    "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
  when: pi is defined and pi


######################
## NODEJS
######################

- name: setup new version of nodejs
  shell: curl -sL https://deb.nodesource.com/setup_6.x |  bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: ensure node is installed
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - nodejs=6*
    - jq

######################
## KAPTURE APP
######################

- name: get kapture repo key
  apt_key:
    url: https://kapture-apt.s3.amazonaws.com/kapture-apt-s3.gpg
    state: present

- name: add kapture repo
  apt_repository:
    repo: "deb https://kapture-apt.s3.amazonaws.com {{ kapture_app_branch }} main"
    update_cache: yes

- name: install kapture
  apt:
    name: kapture
    state: latest


######################
## KAPTURE SETTINGS
######################

- name: if enabled setup flexget token
  include: flexget.yml
  when: flexget_enabled

- name: if enabled setup transmission settings
  include: transmission.yml
  when: transmission_enabled
