---
# tasks file for roles/kapture

- meta: flush_handlers

#######################
### System STUFF
#######################

- include: system.yml 
  when: not container
  
- name: install pip from apt
  apt: 
    pkg: python-pip 
    state: present
  when: ansible_lsb.id != "Raspbian"

- block:
    - name: install pip using easy_install if Raspbian
      apt: name=python-setuptools state=present
    - easy_install: name=pip state=present
  when: ansible_lsb.id == "Raspbian"

- name: install ansible for running locally
  pip: 
    name: "{{ item.name }}" 
    version: "{{ item.version | default(omit) }}" 
    state: present
  when: not container
  with_items:
    - { name: ansible }
    - { name: setuptools, version: 23.0.0 }

######################
## NODEJS
######################

- name: setup nodejs 8.x apt repo
  shell: curl -sL https://deb.nodesource.com/setup_8.x |  bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: ensure node is installed
  apt: 
    pkg: "{{ item }}" 
    state: present
    update_cache: yes
  with_items:
    - nodejs=8*
    - jq

- name: install ngrok if needed
  command: npm install -g ngrok
  when: install_ngrok

######################
## KAPTURE APP
######################

- name: get kapture repo key
  apt_key:
    url: https://kapture-apt.s3.amazonaws.com/kapture-apt-s3.gpg
    state: present

- name: add kapture repo
  apt_repository:
    repo: "deb https://kapture-apt.s3.amazonaws.com {{ kapture_app_branch }} main"
    update_cache: yes

- name: install kapture and kapture-ansible packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - kapture
    - kapture-ansible
    - kapture-iot

- name: start kapture in background if container
  command: nodejs app.js
  async: yes
  args:
    chdir: /var/kapture/server
  environment:
    NODE_ENV: production
  when: container

######################
## KAPTURE SETTINGS
######################

- name: if enabled setup flexget token
  include: flexget.yml
  when: flexget_enabled

- name: if enabled setup transmission settings
  include: transmission.yml
  when: transmission_enabled
